be more strict about matching available version numbers

diff --git a/bin/build-perl b/bin/build-perl
--- a/bin/build-perl
+++ b/bin/build-perl
@@ -28,7 +28,17 @@ function perlbrew_build {
   local perl_version="$1"
   local brewver="${perl_version/-*/}"
   if [[ "$brewver" =~ ^[0-9].[0-9][0-9]?$ ]]; then
-    brewver="$(perlbrew available --all | cut -c3- | grep "^perl-${brewver}." | sort -r -n -t. -k3 | head -1)"
+    brewver="$(
+      perlbrew available --all \
+      | cut -c3- \
+      | grep -E "^perl-${brewver/./\\.}\\.[0-9][0-9]?$" \
+      | sort -r -n -t. -k3 \
+      | head -1
+    )"
+    if [ -z "$brewver" ]; then
+      echo "Unable to find perl for $perl_version!" >&2
+      return 1
+    fi
   fi
 
   brewopts="--notest --noman --verbose"
